### ISSUE TITLE
.cypher files missing after transpilation

### ISSUE THREAD

**Issue by Bastianowicz** [liberation-data/drivine-inspiration#8]
After the build step there are no `.cypher` files in the dist directory. That is because of tsc behaviour to only include ts/js files. How did you manage to get it to work?

> Cannot find module '/****/api/dist/user/repository/userById.cypher'
> Require stack:
> - /****/api/node_modules/@liberation-data/drivine/DrivineInjectionDecorators.js

**Comment by jasperblues** [comment]
This issue has been logged to be fixed. I intended to provide a short-term fix in the meantime, in that Drivine will look for a match in the _current directory_ first. However it appears that this code isn't there! 

```typescript
/**
 * Resolves a resource name given the arguments. The single argument version is for use when a TypeScript path alias
 * is set up. Example @Inject('@/traffic/routesBetween'). This is the original behavior in v1.x, however some users found
 * it puzzling.
 *
 * The two argument version is for when there is not path alias, for example: @Inject(__dirname, 'routesBetween').
 *
 * @param dirNameOrPath Either a directory name or the full path.
 * @param extension The extension of the file, if any.
 * @param resourceName, the file name, given that the dirName is specified as the first argument.
 */
function fileNameFor(dirNameOrPath: string, extension?: string, resourceName?: string): string {
    if (resourceName) {
        const path = `${dirNameOrPath}/${resourceName}`;
        return require.resolve(extension ? `${path}.${extension}` : `${path}`);
    } else {
        return require.resolve(extension ? `${dirNameOrPath}.${extension}` : `${dirNameOrPath}`);
    }
}
```

Looking in the current directory first could be implemented in minutes. However in the meantime can you please write your queries inline (in the code)? For example: 

```typescript
const spec = new QuerySpecification(`MATCH (n) return (n)`)
```

**Comment by Bastianowicz** [comment]
Did it a little like this. I am using a npm script with copyfiles at the moment. Thanks for the reply. I am eager to see the long term solution ☺️ thank you

**Comment by jasperblues** [comment]
>  I am eager to see the long term solution

I have been super busy with client work (new client usually means steep learning curve) however I will try to make time in the next few days. 

The issue has been logged over on the main repo, so you may follow and comment there, if you please.

**Comment by anrolmar** [comment]
I have the same problem.

Ok. I'll do your workaround in the meantime.

Thanks
